import React from "react";

const data = [
  {
    id: 1,
    name: "vishal kumar",
    email: "vishal.k3102@gmail.com",
    stepWalked: 2547,
    stepTarget: 4000,
    performedDate: "15 oct",
    scheduleDate: "25 / 07",
    calorieIntake: 1200,
    calorieTarget: 2000,
    proteinConsumed: 45,
    proteinTarget: 70,
    carbConsumed: 50,
    carbTarget: 70,
    fatConsumed: 30,
    fatTarget: 70,
    feedback: "true",
    proteinName: "PROTEIN",
    carbsName: "CARBS",
    fatName: "FATS",
  },
  {
    id: 2,
    name: "Charvie Sharma",
    email: "charviesharma@gmail.com",
    stepWalked: 2547,
    stepTarget: 4000,
    performedDate: "15 oct",
    scheduleDate: "26 /07",
    calorieIntake: 1200,
    calorieTarget: 2000,
    proteinConsumed: 45,
    proteinTarget: 70,
    carbConsumed: 50,
    carbTarget: 70,
    fatConsumed: 30,
    fatTarget: 70,
    feedback: "true",
    proteinName: "PROTEIN",
    carbsName: "CARBS",
    fatName: "FATS",
  },
  {
    id: 3,
    name: "Charvie Sharma",
    email: "charviesharma@gmail.com",
    stepWalked: 2547,
    stepTarget: 4000,
    performedDate: "15 oct",
    scheduleDate: "25 /10",
    calorieIntake: 1200,
    calorieTarget: 2000,
    proteinConsumed: 45,
    proteinTarget: 70,
    carbConsumed: 50,
    carbTarget: 70,
    fatConsumed: 30,
    fatTarget: 70,
    feedback: "false",
    proteinName: "PROTEIN",
    carbsName: "CARBS",
    fatName: "FATS",
  },
];

export default data;
